create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  razorpay_order_id text not null unique,
  razorpay_payment_id text unique,
  receipt text not null unique,
  status text not null check (status in ('pending_payment', 'paid', 'preparing', 'out_for_delivery', 'completed', 'cancelled')),
  customer_name text not null,
  customer_phone text not null,
  delivery_address text not null,
  landmark text,
  pincode text not null,
  instructions text,
  items jsonb not null,
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer not null check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
